### ISSUE TITLE
can't run the quick demo

### ISSUE THREAD

**Issue by KobeDeShow** [rkadlec/asreader#1]
hi, rkadlec,  i run the  quick-start-cbt-ne.sh  ,but i  get the error, what's the problem , thank you in advance!

Computing new vocabulary for file ../data/CBTest/data/cbtest_NE_train.txt.
Processed line 100000
Processed line 200000
Processed line 300000
Processed line 400000
Processed line 500000
Processed line 600000
Processed line 700000
Processed line 800000
Processed line 900000
Processed line 1000000
Processed line 1100000
Processed line 1200000
Processed line 1300000
Processed line 1400000
Processed line 1500000
Processed line 1600000
Processed line 1700000
Processed line 1800000
Processed line 1900000
Processed line 2000000
Processed line 2100000
Processed line 2200000
Processed line 2300000
STATISTICS
Total words: 53825761
Total distinct words: 60278
STATISTICS
Total words: 942535
Total distinct words: 10720
Added 920 new words from file ../data/CBTest/data/cbtest_NE_valid_2000ex.txt to previous vocabulary.
STATISTICS
Total words: 1213447
Total distinct words: 13277
Added 1311 new words from file ../data/CBTest/data/cbtest_NE_test_2500ex.txt to previous vocabulary.
  File "text_comprehension/as_reader.py", line 166, in <module>
    exp.execute()
  File "/data1/arvinjin/text/test_as/asreader-master/asreader/text_comprehension/text_comprehension_base.py", line 386, in execute
    **self.args.evaluate_every_n)
  File "/data1/arvinjin/text/test_as/asreader-master/asreader/text_comprehension/monitoring.py", line 79, in **init**
    self._evaluator = MemoryDatasetEvaluator([context_attention, context,y_hat,y,candidates, candidates_mask, context_mask,x_mask,x], updates)
  File "/data1/arvinjin/text/test_as/asreader-master/asreader/text_comprehension/monitoring.py", line 233, in __init__
    self.theano_buffer = AggregationBuffer(theano_variables)
  File "/usr/lib/python2.7/site-packages/blocks-0.2.0-py2.7.egg/blocks/monitoring/evaluators.py", line 127, in **init**
    _validate_variable_names(variables)
  File "/usr/lib/python2.7/site-packages/blocks-0.2.0-py2.7.egg/blocks/monitoring/evaluators.py", line 23, in _validate_variable_names
    raise ValueError('Variables must have names: {}'.format(none_names))
ValueError: Variables must have names: [Elemwise{second,no_inplace}.0]

**Comment by soon2soon** [comment]
I have the same issue. any solution would be appreciated! Thanks.

**Comment by rkadlec** [comment]
Hi, sorry, I missed the first email notifying about this issue. 
This problem appears when you use the latest Blocks.
Try some older release and it should work. For instance, I tested it successfully today with Blocks commit 359afad119f8c6ac0ebc3cc6ec6e6475656babae.

To downgrade Blocks run:
pip install git+https://github.com/mila-udem/blocks.git@359afad119f8c6ac0ebc3cc6ec6e6475656babae

Let me know whether it solved the issue on your side too.

**Comment by soon2soon** [comment]
Hi rkadlec. 

Thanks for your immediate reply. 
Your suggestion resolved my problem. It worked as charm. 

Thank you!

Regards

**Comment by rkadlec** [comment]
Good to hear that. I already pushed the fix.
