### ISSUE TITLE
Using pre-trained word embedding instead of random initialized lookup table?

### ISSUE THREAD

**Issue by soon2soon** [rkadlec/asreader#2]
Hi rkadlec,

I would like to initialize the lookup table with pre-trained embeddings such as Word2Vec or GloVe in the code. 

I tried to figure out how to load other word vector model into blocks LookupTable but there is little information about it.   

Do you have any idea for this problem?  FYI, I'm using gensim Word2Vec tool to load pre-trained model and trying to initialize lookup table with it.

Thanks in advance!

**Comment by rkadlec** [comment]
Hi, try something like:
lookup_table = LookupTable(... weights_init=Constant(my_word2vec))
where "my_word2vec" is a Numpy matrix with word vectors

**Comment by soon2soon** [comment]
Hi, 

Sorry for rate reply.
It seems work with your suggestion.  Thank you!

**Comment by rkadlec** [comment]
I am glad to hear that. By the way we also did some experiments with pre-trained word embeddings but in our experience it is much more promising just to use more in domain training data when you want to improve you final system. We report these experiments in our latest paper https://arxiv.org/abs/1610.00956.
