### ISSUE TITLE
Visualization question

### ISSUE THREAD

**Issue by ganganFighting** [rkadlec/asreader#3]
I run the ./quick-start-cnn.sh script, it can output predictions and logs,
but there is no html file that visualize the attention. 
how to set the argument? 
Thanks a lot

**Comment by rkadlec** [comment]
Hi, simply erase --no_html from this line https://github.com/rkadlec/asreader/blob/master/asreader/quick-start-generic.sh#L16
this will output attentions every time the model is evaluated on test and valid data. However, this might consume a lot of disk space.

Another option is to train with --no_html and visualize just attention from trained model loaded by --load_model option.
